# 1. กำหนดลำดับขั้นตอน
stages:
  - build
  - deploy

# 2. ตั้งค่าตัวแปรกลาง
variables:
  NODE_IMAGE: node:20-slim

# --- ✨ เพิ่มระบบ Cache ตรงนี้ ✨ ---
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vue-frontend/node_modules/

# 3. ขั้นตอนการประกอบร่าง (Build)
build_vue_app:
  stage: build
  image: $NODE_IMAGE
  script:
    - cd vue-frontend
    - echo "เริ่มติดตั้ง Library..."
    - npm install
    - echo "เริ่ม Build โปรเจกต์..."
    - npm run build
  artifacts:
    paths:
      - vue-frontend/dist/
    expire_in: 1 week

# 4. ขั้นตอนการนำไปใช้งาน (Deploy)
deploy-vercel:
  stage: deploy
  image: node:20
  script:
    - npm install --global vercel
    - cd vue-frontend
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
  only:
    - main
